---
- hosts: ZabbixWebServers
  roles:
    - mrdatamapper.akademiano_postgresql_facts
    - mrdatamapper.akademiano_zabbix_server_facts
    - mrdatamapper.akademiano_prepare_zabbix_server
    - mrdatamapper.akademiano_prepare_zabbix_web
    - { role: dj-wasabi.zabbix-web, become: yes  }
