---
- hosts: Linux
  gather_facts: False
  vars:
    ansible_ssh_extra_args: "{{ ansible_ssh_extra_args_base }} -o ControlMaster=no -o ControlPath=none"
  
  tasks:
  - apt:
      name: python-dnspython
      state: present
    become: yes
    become_user: root
    delegate_to: localhost

  - include_tasks: akademiano-hostkeys-host.yml
    loop:  "{{ ansible_play_hosts }}"
    loop_control:
      loop_var: host

