---
- hosts: Linux
  gather_facts: False
  vars:
    ansible_ssh_extra_args: "{{ ansible_ssh_extra_args_base }} -o ControlMaster=no -o ControlPath=none"
  
  tasks:
  - include_tasks: akademiano-hostkeys-host.yml
    loop:  "{{ ansible_play_hosts }}"
    loop_control:
      loop_var: host

